"""Add indexes for leaderboard queries

Revision ID: 539d94d4f5e3
Revises: 93a003f44b87
Create Date: 2025-12-19 14:48:35.981397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539d94d4f5e3'
down_revision: Union[str, None] = '93a003f44b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scores_difficulty'), 'scores', ['difficulty'], unique=False)
    op.create_index(op.f('ix_scores_game_mode'), 'scores', ['game_mode'], unique=False)
    op.create_index('ix_scores_leaderboard', 'scores', ['game_mode', 'difficulty', 'score'], unique=False)
    op.create_index('ix_scores_leaderboard_user', 'scores', ['user_id', 'game_mode', 'difficulty', 'score'], unique=False)
    op.create_index(op.f('ix_scores_score'), 'scores', ['score'], unique=False)
    op.create_index('ix_scores_weekly', 'scores', ['game_mode', 'difficulty', 'created_at', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_weekly', table_name='scores')
    op.drop_index(op.f('ix_scores_score'), table_name='scores')
    op.drop_index('ix_scores_leaderboard_user', table_name='scores')
    op.drop_index('ix_scores_leaderboard', table_name='scores')
    op.drop_index(op.f('ix_scores_game_mode'), table_name='scores')
    op.drop_index(op.f('ix_scores_difficulty'), table_name='scores')
    # ### end Alembic commands ###
