"""initial_migration

Revision ID: 93a003f44b87
Revises: 
Create Date: 2025-12-17 16:09:17.429706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a003f44b87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('coin_reward', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_achievement_id'), 'achievements', ['achievement_id'], unique=True)
    op.create_table('battle_pass_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('levels_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_pass_seasons_season_id'), 'battle_pass_seasons', ['season_id'], unique=True)
    op.create_index(op.f('ix_battle_pass_seasons_start_date'), 'battle_pass_seasons', ['start_date'], unique=False)
    op.create_table('multiplayer_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('room_code', sa.String(length=10), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('food_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('power_ups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('game_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiplayer_games_game_id'), 'multiplayer_games', ['game_id'], unique=True)
    op.create_index(op.f('ix_multiplayer_games_room_code'), 'multiplayer_games', ['room_code'], unique=False)
    op.create_table('notification_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=True),
    sa.Column('recipients_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_history_sent_at'), 'notification_history', ['sent_at'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_job_id'), 'scheduled_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_scheduled_jobs_next_run_time'), 'scheduled_jobs', ['next_run_time'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('prize_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_start_date'), 'tournaments', ['start_date'], unique=False)
    op.create_index(op.f('ix_tournaments_tournament_id'), 'tournaments', ['tournament_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.Column('total_games_played', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('subscribed_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('friend_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendship')
    )
    op.create_index(op.f('ix_friendships_friend_id'), 'friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_table('multiplayer_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('player_index', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.Column('snake_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('snake_color', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['multiplayer_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiplayer_players_game_id'), 'multiplayer_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_multiplayer_players_user_id'), 'multiplayer_players', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('receipt_data', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_error', sa.Text(), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renewing', sa.Boolean(), nullable=True),
    sa.Column('content_unlocked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchases_transaction_id'), 'purchases', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('game_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('foods_eaten', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('game_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_created_at'), 'scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    op.create_table('tournament_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('prize_claimed', sa.Boolean(), nullable=True),
    sa.Column('prize_amount', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='unique_tournament_entry')
    )
    op.create_index(op.f('ix_tournament_entries_tournament_id'), 'tournament_entries', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_tournament_entries_user_id'), 'tournament_entries', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('achievement_id', sa.UUID(), nullable=True),
    sa.Column('current_progress', sa.Integer(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_battle_pass_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('has_premium', sa.Boolean(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('total_xp_earned', sa.Integer(), nullable=True),
    sa.Column('claimed_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['battle_pass_seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', name='unique_user_season_progress')
    )
    op.create_index(op.f('ix_user_battle_pass_progress_season_id'), 'user_battle_pass_progress', ['season_id'], unique=False)
    op.create_index(op.f('ix_user_battle_pass_progress_user_id'), 'user_battle_pass_progress', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    sa.Column('music_enabled', sa.Boolean(), nullable=True),
    sa.Column('vibration_enabled', sa.Boolean(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_premium_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('premium_tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('battle_pass_active', sa.Boolean(), nullable=True),
    sa.Column('battle_pass_expires_at', sa.DateTime(), nullable=True),
    sa.Column('battle_pass_tier', sa.Integer(), nullable=True),
    sa.Column('owned_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owned_powerups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owned_cosmetics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tournament_entries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_premium_content_user_id'), 'user_premium_content', ['user_id'], unique=True)
    op.create_table('game_replays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('score_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('replay_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_replays_user_id'), 'game_replays', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_replays_user_id'), table_name='game_replays')
    op.drop_table('game_replays')
    op.drop_index(op.f('ix_user_premium_content_user_id'), table_name='user_premium_content')
    op.drop_table('user_premium_content')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_battle_pass_progress_user_id'), table_name='user_battle_pass_progress')
    op.drop_index(op.f('ix_user_battle_pass_progress_season_id'), table_name='user_battle_pass_progress')
    op.drop_table('user_battle_pass_progress')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_tournament_entries_user_id'), table_name='tournament_entries')
    op.drop_index(op.f('ix_tournament_entries_tournament_id'), table_name='tournament_entries')
    op.drop_table('tournament_entries')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_created_at'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_transaction_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_multiplayer_players_user_id'), table_name='multiplayer_players')
    op.drop_index(op.f('ix_multiplayer_players_game_id'), table_name='multiplayer_players')
    op.drop_table('multiplayer_players')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_friend_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tournaments_tournament_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_start_date'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_scheduled_jobs_next_run_time'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_job_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_notification_history_sent_at'), table_name='notification_history')
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_multiplayer_games_room_code'), table_name='multiplayer_games')
    op.drop_index(op.f('ix_multiplayer_games_game_id'), table_name='multiplayer_games')
    op.drop_table('multiplayer_games')
    op.drop_index(op.f('ix_battle_pass_seasons_start_date'), table_name='battle_pass_seasons')
    op.drop_index(op.f('ix_battle_pass_seasons_season_id'), table_name='battle_pass_seasons')
    op.drop_table('battle_pass_seasons')
    op.drop_index(op.f('ix_achievements_achievement_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
